# see compatibility table: https://github.com/docker/compose/releases
# see networking info: https://docs.docker.com/compose/networking/
version: '2.4'
services:
  mongo:
    build:
      context: mongo/
      user: root
      volumes: mongodata:/data/db
      ports:        
        - 27017:27017      
  nesspoll-users:
    build:
      context: services/users/   
    user: root
    ports:
      - 7000:7000      
    container_name: nesspoll-users   
    depends_on:
      - mongo    
  nesspoll:
    build:
      context: nesspoll/
    privileged: true
    user: root
    ports:
      - 6000:6000      
    container_name: nesspoll
    depends_on:
      - nesspoll-users
  
    