node {
    def commit_id
    stage('Preparation') {
        checkout scm
        sh "git rev-parse --short HEAD > .git/commit-id"
        commit_id = 'latest'
    }
//    stage('test') {
//        nodejs(nodeJSInstallationName: 'nodejs') {
//            sh 'npm install --only=dev'
//            sh 'npm test'
//        }
//    }
    docker.build("my-image:${commit_id}")
}
