FROM jenkins

USER root
RUN apt-get -qq update \
   && apt-get -qq -y install \
   curl \
   && apt-get -y install sudo

RUN curl -sSL https://get.docker.com/ | sh

RUN usermod -a -G staff jenkins

USER jenkins